// import type {Metadata} from "next";
// import {Inter} from "next/font/google";
import "./globals.css";
import {Header} from "./Components/Header/Header.jsx";
import Footer from "./Components/Footer/Footer.jsx";
// import {CartProvider} from "react-use-cart";
// "./Components/CartProvider.jsx"
// import { CartProvider } from './Components/CartProvider.jsx';

// const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
// 	title: "HNG task stage 2",
// 	description: "Generated by create next app",
// };

export default function RootLayout({children}) {
	return (
		
			<html lang='en'>
			<Header/>
			<body className>
			{/* <CartProvider>	{children} </CartProvider> */}
			{children} 
			</body>
			<Footer />
		</html>
		
	);
}
